name: Minestom Gradle CI

defaults:
  run:
    working-directory: ./

on:
  push:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Node 12
        uses: actions/setup-node@v2
        with:
          node-version: '12'
      - uses: pnpm/action-setup@v1.2.1
        with:
          version: 4.11.1
      - name: Install dependencies
        run: pnpm install
      - name: Build website
        run: pnpm run build